server:
  port: 8087

spring:
  application:
    name: notification-service
  datasource:
    url: ${DBMS_CONNECTION:jdbc:mysql://localhost:3306/notificationdb_salonbooking?createDatabaseIfNotExist=true}
    username: ${DBMS_USERNAME:root}
    password: ${DBMS_PASSWORD:root}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: "http://localhost:8070/eureka/"
