server:
  port: 8086

spring:
  application:
    name: payment-service
  datasource:
    url: ${DBMS_CONNECTION:jdbc:mysql://localhost:3306/paymentdb_salonbooking}
    username: ${DBMS_USERNAME:root}
    password: ${DBMS_PASSWORD:root}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

stripe:
  api:
    key: ""
