server:
    port: 8084

spring:
  application:
    name: service-offering
  datasource:
    url: ${DBMS_CONNECTION:jdbc:mysql://localhost:3306/service_offering_salonbooking?useSSL=false&serverTimezone=UTC}
    username: ${DBMS_PASSWORD:root}
    password: ${DBMS_PASSWORD:root}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
